set(CMAKE_SYSTEM_NAME Windows)

set(TOOLCHAIN "x86_64-w64-mingw32")
set(TOOLCHAIN_SUFFIX "-posix")

set(CMAKE_C_COMPILER "${TOOLCHAIN}-gcc${TOOLCHAIN_SUFFIX}")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN}-g++${TOOLCHAIN_SUFFIX}")
set(CMAKE_RC_COMPILER "${TOOLCHAIN}-windres${TOOLCHAIN_SUFFIX}")
set(CMAKE_AR "${TOOLCHAIN}-ar${TOOLCHAIN_SUFFIX}")
set(CMAKE_RANLIB "${TOOLCHAIN}-ranlib${TOOLCHAIN_SUFFIX}")
set(CMAKE_STRIP "${TOOLCHAIN}-strip${TOOLCHAIN_SUFFIX}")
set(CMAKE_NM "${TOOLCHAIN}-nm${TOOLCHAIN_SUFFIX}")
