set(CMAKE_SYSTEM_NAME Windows)

set(TOOLCHAIN "x86_64-w64-mingw32")
set(TOOLCHAIN_SUFFIX "-posix")

set(CMAKE_C_COMPILER "${TOOLCHAIN}-gcc${TOOLCHAIN_SUFFIX}")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN}-g++${TOOLCHAIN_SUFFIX}")
set(CMAKE_RC_COMPILER "${TOOLCHAIN}-windres")
set(CMAKE_AR "${TOOLCHAIN}-ar")
set(CMAKE_RANLIB "${TOOLCHAIN}-ranlib")
set(CMAKE_STRIP "${TOOLCHAIN}-strip")
set(CMAKE_NM "${TOOLCHAIN}-nm")
set(CMAKE_LINKER "${TOOLCHAIN}-ld")