name: Linux build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ build-essential libcap-dev
          sudo apt-get install -y gcc-12 g++-12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: cmake .. -DTORPP=ON -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/linux.cmake

      - name: Build
        working-directory: build
        run: cmake --build . --config Release

      - name: Upload torpp artifact
        uses: actions/upload-artifact@v3
        with:
          name: torpp
          path: build/

      - name: Upload libonionpp-shared artifact
        uses: actions/upload-artifact@v3
        with:
          name: libonionpp-shared.so
          path: build/

      - name: Upload libonionpp-static artifact
        uses: actions/upload-artifact@v3
        with:
          name: libonionpp-static.so
          path: build/
