name: Linux build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ build-essential

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: cmake .. -DTORPP=ON

      - name: Build
        working-directory: build
        run: cmake --build . --config Release
