name: Windows build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
          choco install visualstudio2022buildtools -y
          choco install visualstudio2022-workload-vctools -y

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: cmake .. -G "Visual Studio 17 2022" -A x64

      - name: Build the project
        working-directory: build
        run: cmake --build . --config Release
