name: Windows build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mingw-w64-x86-64-dev \
            gcc-mingw-w64-x86-64-posix \
            g++-mingw-w64-x86-64-posix \
            binutils-mingw-w64-x86-64

      - name: Version info
        run: |
          echo "PATH: $PATH"
          x86_64-w64-mingw32-gcc-posix --version
          x86_64-w64-mingw32-g++-posix --version
          x86_64-w64-mingw32-ld --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/windows.cmake

      - name: Build
        working-directory: build
        run: cmake --build . --config Release

      - name: Upload torpp artifact
        uses: actions/upload-artifact@v3
        with:
          name: torpp.exe
          path: build/torpp.exe

      - name: Upload libonionpp-static artifact
        uses: actions/upload-artifact@v3
        with:
          name: libonionpp-static.a
          path: build/libonionpp-static.a
