name: Windows build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: cmake .. -DCMAKE_SYSTEM_NAME=Windows

      - name: Build
        working-directory: build
        run: cmake --build . --config Release
