name: Windows build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64-posix

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/windows.cmake

      - name: Build
        working-directory: build
        run: cmake --build . --config Release

      - name: Upload torpp artifact
        uses: actions/upload-artifact@v3
        with:
          name: torpp.exe
          path: build/

      - name: Upload libonionpp-static artifact
        uses: actions/upload-artifact@v3
        with:
          name: libonionpp-static.a
          path: build/
